### ISSUE TITLE
Throw ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by chambtinno** [analogue/iotop#6]
My os is : Manjaro Linux
Python Version: 3.7
The package that installed: https://www.archlinux.org/packages/community/any/iotop/

Console Print screen:
https://postimg.cc/6ThHBMNT

**Comment by TCB13** [comment]
I've the same issue here with Armbian here:

>  iotop
> Traceback (most recent call last):
>   File "/usr/sbin/iotop", line 17, in <module>
>     main()
>   File "/usr/lib/python3/dist-packages/iotop/ui.py", line 620, in main
>     main_loop()
>   File "/usr/lib/python3/dist-packages/iotop/ui.py", line 610, in <lambda>
>     main_loop = lambda: run_iotop(options)
>   File "/usr/lib/python3/dist-packages/iotop/ui.py", line 508, in run_iotop
>     return curses.wrapper(run_iotop_window, options)
>   File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
>     return func(stdscr, *args, **kwds)
>   File "/usr/lib/python3/dist-packages/iotop/ui.py", line 501, in run_iotop_window
>     ui.run()
>   File "/usr/lib/python3/dist-packages/iotop/ui.py", line 155, in run
>     self.process_list.duration)
>   File "/usr/lib/python3/dist-packages/iotop/ui.py", line 434, in refresh_display
>     lines = self.get_data()
>   File "/usr/lib/python3/dist-packages/iotop/ui.py", line 415, in get_data
>     return list(map(format, processes))
>   File "/usr/lib/python3/dist-packages/iotop/ui.py", line 388, in format
>     cmdline = p.get_cmdline()
>   File "/usr/lib/python3/dist-packages/iotop/data.py", line 292, in get_cmdline
>     proc_status = parse_proc_pid_status(self.pid)
>   File "/usr/lib/python3/dist-packages/iotop/data.py", line 196, in parse_proc_pid_status
>     key, value = line.split(':\t', 1)
> ValueError: not enough values to unpack (expected 2, got 1)

**Some system information**:

    lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:    Debian GNU/Linux 9.6 (stretch)
    Release:        9.6
    Codename:       stretch

    uname -a
    Linux testxyz 4.4.162-rk3399 #41 SMP Fri Oct 26 14:03:47 CEST 2018 aarch64 GNU/Linux

**Comment by gbwizard** [comment]
Some here with modern Gentoo:
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	Gentoo
Description:	Gentoo Base System release 2.6
Release:	2.6
Codename:	n/a

$ uname -a
Linux workstation 4.4.164-gentoo

/ $ iotop --version
iotop 0.6

**Comment by elixx** [comment]
I am also affected on arm64.

```

root@rockpro64:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
root@rockpro64:~# uname -a
Linux rockpro64 4.4.167-1181-rockchip-ayufan-gd20421e03128 #1 SMP Tue Apr 9 17:44:02 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
root@rockpro64:~# iotop --version
iotop 0.6
root@rockpro64:~# python --version
Python 2.7.15rc1
root@rockpro64:~# iotop
Traceback (most recent call last):
  File "/usr/sbin/iotop", line 17, in <module>
    main()
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 620, in main
    main_loop()
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 610, in <lambda>
    main_loop = lambda: run_iotop(options)
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 508, in run_iotop
    return curses.wrapper(run_iotop_window, options)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 501, in run_iotop_window
    ui.run()
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 155, in run
    self.process_list.duration)
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 434, in refresh_display
    lines = self.get_data()
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 415, in get_data
    return list(map(format, processes))
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 388, in format
    cmdline = p.get_cmdline()
  File "/usr/lib/python3/dist-packages/iotop/data.py", line 292, in get_cmdline
    proc_status = parse_proc_pid_status(self.pid)
  File "/usr/lib/python3/dist-packages/iotop/data.py", line 196, in parse_proc_pid_status
    key, value = line.split(':\t', 1)
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by Noobgam** [comment]
Got to this error too, but this commit https://github.com/analogue/iotop/commit/f9f3924b9d187cf026785b1533ef66ffc631d029 already fixes the issue. Perhaps installing from source will fix the issue for all of you, most likely distro has outdated package.

Happens for example when supplementary group list for the process is empty, when parsing
`Groups:\n`.
